Include model.eval()
udacity/deep-learning-v2-pytorch pull request #397
Opened 2022-03-28 14:11 UTC by salehsargolzaee

Setting all the layers in the model to evaluation mode before evaluation to turn off dropout layer.

2022-03-29 21:06 UTC, ronny-udacity requested changes
Thanks for the PR request. The `model.train()` needs to be added back if we're going to use `model.eval()`

2022-03-30 04:41 UTC, salehsargolzaee commented
> 

I don't think it's necessary since we always evaluate the model after all epochs are done in this code, so the default mode is  "train mode" before that (after model initialization). However, it's safe to add it.

2022-03-30 04:45 UTC, salehsargolzaee commented
> Thanks for the PR request. The `model.train()` needs to be added back if we're going to use `model.eval()`

I don't think `model.train()` is necessary since we always evaluate the model after all the epochs are done in this code, so the default mode is `train mode` before the evaluation steps. However, it's safe to add it.

2022-03-30 14:54 UTC, ronny-udacity approved these changes

2022-03-30 14:55 UTC, merged